apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: httpbin-rt-80
  namespace: gloo-mesh
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: cluster1-north-south-gw-80
      namespace: gloo-mesh
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: httpbin
      matchers:
      - uri:
          exact: /get
      forwardTo:
        destinations:
        - port:
            number: 8000
          ref:
            cluster: cluster1
            name: in-mesh
            namespace: httpbin
