apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: httpbin-rt-443
  namespace: gloo-mesh
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: cluster1-north-south-gw-443
      namespace: gloo-mesh
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: httpbin
      matchers:
      - uri:
          exact: /get
      - uri:
          exact: /callback
      forwardTo:
        destinations:
        - kind: VIRTUAL_DESTINATION
          port:
            number: 8000
          ref:
            name: httpbin-vd
            namespace: gloo-mesh
            cluster: mgmt