apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  labels:
    expose: "true"
  name: httpbin-vd
  namespace: gloo-mesh
spec:
  hosts:
  - httpbin.internal
  ports:
  - number: 8000
    protocol: HTTP
  services:
  - workspace: wildcard
    labels:
      app: in-mesh