# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- gateway-cert.yaml
- gateway-clusterissuer.yaml
#- glcm-ew-mgmt.yaml
- glcm-ns-mgmt.yaml
- ilcm.yaml

