# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- ../../base/active/
- argocd-cluster1-rt-80.yaml
- gloo-mesh-cluster1-virtualgateway-80.yaml
- gloo-mesh-cluster1-virtualgateway-443.yaml