apiVersion: admin.gloo.solo.io/v2
kind: RootTrustPolicy
metadata:
  name: root-trust-policy
  namespace: gloo-mesh
spec:
  applyToMeshes:
    istio:
      clusterSelector:
        - roottrust: shared
      namespace: istio-system
  config:
    autoRestartPods: true
    mgmtServerCa:
      generated: {}