apiVersion: admin.gloo.solo.io/v2
kind: RootTrustPolicy
metadata:
  name: root-trust-policy
  namespace: gloo-mesh
spec:
  config:
    autoRestartPods: false
    mgmtServerCa:
      #generated: {}
      secretRef:
        name: dummy-signing-cert
        namespace: gloo-mesh