#apiVersion: resilience.policy.gloo.solo.io/v2
#kind: FailoverPolicy
#metadata:
#  name: failover
#  namespace: bookinfo-frontends
#spec:
#  applyToDestinations:
#  - kind: VIRTUAL_DESTINATION
#    selector:
#      labels:
#        failover: "true"
#  config:
#    localityMappings: []
#---
#apiVersion: resilience.policy.gloo.solo.io/v2
#kind: OutlierDetectionPolicy
#metadata:
#  name: outlier-detection
#  namespace: bookinfo-frontends
#spec:
#  applyToDestinations:
#  - kind: VIRTUAL_DESTINATION
#    selector:
#      labels:
#        failover: "true"
#  config:
#    baseEjectionTime: 30s
#    consecutiveErrors: 2
#    interval: 5s
#    maxEjectionPercent: 100
#---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: reviews
  namespace: bookinfo-backends
spec:
  hosts:
  - reviews.bookinfo-backends.svc.cluster.local
  http:
  - forwardTo:
      destinations:
      - port:
          number: 9080
        ref:
          cluster: cluster2
          name: reviews
          namespace: bookinfo-backends
        subset:
          version: v3
    matchers:
    - uri:
        prefix: /
    name: reviews
  workloadSelectors:
  - selector:
      labels:
        app: productpage
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: productpage
  namespace: bookinfo-frontends
spec:
  hosts:
  - 'bookinfo-local.glootest.com'
  http:
  - forwardTo:
      destinations:
      - kind: VIRTUAL_DESTINATION
        port:
          number: 9080
        ref:
          name: productpage
          namespace: bookinfo-frontends
    matchers:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    name: productpage
  virtualGateways:
  - name: north-south-gw
    namespace: istio-gateways
    cluster: mgmt
  workloadSelectors: []
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  labels:
    expose: "true"
    failover: "true"
  name: productpage
  namespace: bookinfo-frontends
spec:
  hosts:
  - productpage.global
  ports:
  - number: 9080
    protocol: HTTP
  services:
  - labels:
      app: productpage
    namespace: bookinfo-frontends
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: north-south-gw
  namespace: istio-gateways
spec:
  listeners:
  - http: {}
    port:
      number: 443
    tls:
      mode: SIMPLE
      secretName: tls-secret
  workloads:
  - selector:
      labels:
        istio: ingressgateway
  #- selector:
  #    cluster: cluster1
  #    labels:
  #      istio: ingressgateway
  #- selector:
  #    cluster: cluster2
  #    labels:
  #      istio: ingressgateway