apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: lambda
  namespace: lambda
spec:
  exportTo:
  - workspaces:
    - name: ops-team
  importFrom:
  - workspaces:
    - name: ops-team