apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: all-gateways
  namespace: gloo-mesh
spec:
  installations:
      # The revision for this installation, such as 1-14
    - gatewayRevision: 1-15
      # List all workload clusters to install Istio into
      clusters:
      - name: mgmt
        # If set to true, the spec for this revision is applied in the cluster
        activeGateway: true
      istioOperatorSpec:
        # No control plane components are installed
        profile: empty
        # Solo.io Istio distribution repository; required for Gloo Istio.
        # You get the repo key from your Solo Account Representative.
        hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
        # The Solo.io Gloo Istio tag
        tag: 1.15.1-solo
        components:
          ingressGateways:
            - enabled: true
              k8s:
                service:
                  ports:
                    - name: http2
                      port: 80
                      protocol: TCP
                      targetPort: 8080
                    - name: https
                      port: 443
                      protocol: TCP
                      targetPort: 8443
                  selector:
                    app: istio-ingressgateway
                    istio: ingressgateway
                  type: LoadBalancer
              name: istio-ingressgateway
              namespace: istio-ingress
            - enabled: true
              name: istio-eastwestgateway
              namespace: istio-eastwest
              label:
                istio: eastwestgateway
              k8s:
                env:
                  - name: ISTIO_META_ROUTER_MODE
                    value: sni-dnat
                service:
                  ports:
                    - port: 15443
                      targetPort: 15443
                      # Gloo Mesh looks for this default name 'tls' on a gateway
                      name: tls
                  selector:
                    istio: eastwestgateway
                  type: LoadBalancer