apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: gloo-mesh
spec:
  isCA: true
  duration: 2160h # 90d
  #secretName: istio-ca
  secretName: dummy-signing-cert
  commonName: istio-ca
  subject:
    organizations:
    - cluster.local
    - cert-manager
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io