apiVersion: admin.gloo.solo.io/v2
kind: ExtAuthServer
metadata:
  name: default-server
  namespace: gloo-mesh-config
spec:
  destinationServer:
    port:
      number: 8083
    ref:
      cluster: cluster1
      name: ext-auth-service
      namespace: gloo-mesh-addons
  #failureModeAllow: true
  #statusOnError: 404