apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: httpbin
  namespace: gloo-mesh-app-config
spec:
  applyToRoutes:
  - route:
      labels:
        oauth: "true"
  config:
    server:
      name: default-server
      namespace: gloo-mesh-config
      cluster: mgmt
    glooAuth:
      configs:
      - oauth2:
          oidcAuthorizationCode:
            appUrl: https://httpbin-local.glootest.com:8443
            callbackPath: /callback
            clientId: 0oa5zoq0xoGKtOSpg5d7
            clientSecretRef:
              name: httpbin-oidc-client-secret
              namespace: istio-gateways
            issuerUrl: https://dev-22653158.okta.com/oauth2/default
            session:
              failOnFetchFailure: true
              redis:
                cookieName: okta-session
                options:
                  host: redis.gloo-mesh-addons:6379
                allowRefreshing: false
              cookieOptions:
                maxAge: "1800"
            scopes:
            - email
            logoutPath: /logout
            afterLogoutUrl: /get
            #headers:
              #idTokenHeader: Jwt
              #idTokenHeader: x-id-token
              #accessTokenHeader: x-access-token