apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: gateways
  namespace: gloo-mesh-config
spec:
  exportTo:
  - resources:
    - kind: ALL
    workspaces:
    - selector:
        allow_ingress: "true"
  importFrom:
  - resources:
    - kind: ALL
    - kind: ALL
      labels:
        expose: "true"
    workspaces:
    - selector:
        allow_ingress: "true"
  options:
    federation:
      enabled: true
      hostSuffix: global