apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  labels:
    expose: "true"
  name: productpage
  namespace: gloo-mesh-app-config
spec:
  hosts:
  - productpage.global
  ports:
  - number: 9080
    protocol: HTTP
  services:
  - labels:
      app: productpage
    namespace: bookinfo-frontends