# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- ../../base/active/

patchesStrategicMerge:
- patch/gloo-mesh-addons.yaml
- patch/gloo-mesh-agent.yaml
- patch/gloo-mesh-crds.yaml
- patch/gloo-mesh-ee-helm.yaml