apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: wildcard
  namespace: gloo-mesh
spec:
  exportTo:
  - workspaces:
    - name: '*'
  importFrom:
  - workspaces:
    - name: '*'
  options:
    federation:
      enabled: true
      hostSuffix: global
      serviceSelector:
      - workspace: wildcard
        #labels: 
        #  app: in-mesh